### ISSUE TITLE
Buttons turned pink

### ISSUE THREAD

**Issue by bradydjohnson** [glutanimate/bettertags-public#4] opened 2020-01-24 00:48 UTC
#### Problem description

Fields & Cards buttons are changed to a pink text.
![image](https://user-images.githubusercontent.com/6741590/73036316-cb558600-3e10-11ea-928c-5e0b2a558a21.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

```
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Mac 10.15.2
Flags: frz=True ao=True sv=2

Add-ons:

Edit Field During Review (disabled)
Speed Focus Mode auto-alert auto-reveal auto-fail
Special Fields
Pretzel Logic Retention Benchmarking (disabled)
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags (disabled)
load balancer (disabled)
Symbols
Night Mode
Pop-up Dictionary beta
More Decks Stats and Time Left (disabled)
Hint Hotkeys
Study Logger (disabled)
Customize Sidebar
Load Balanced Scheduler
Card Info During Review
Customize Keyboard Shortcuts
Button Colours Good Again
ReMemorize Rescheduler with sibling and logging v121 (disabled)
Clickable Tags v10
Ankidown - The advanced importer for Anki (disabled)
Frozen Fields
Blitzkrieg II - Advanced Browser Sidebar BETA5 (disabled)
Pokemanki for both Anki 20 and 21 (disabled)
Syllabus - Anki Statistics and Export by Tag and Deck
More Overview Stats 21 (disabled)
Echelon - Improved Hierarchical Tags for Anki 21 (disabled)
Slackers Delight PostponeDefer Button (disabled)
Free_Weekend_Load_Balancer-master (disabled)
BetterTags
Cloze Overlapper
Review Heatmap
```

**Comment by glutanimate** [comment] 2020-01-24 00:58
Thanks for the report, Brady! Huh, that's one of the weirdest bugs I've ever seen. BetterTags doesn't touch the editor area, so if this is caused by BetterTags it must be some incredibly weird interaction on a deep widget rendering level or something like that.

A few questions that might help me dig deeper into this:

1. Can you reliably reproduce this every time you open the browser or was it a one time thing?
2. If you start Anki while holding down shift, does the issue disappear? (this will disable all add-ons temporarily)
3. Does it disappear if you disable BetterTags and then restart Anki?
4. Does it disappear if you disable all add-ons other than BetterTags?

Thanks again!

**Comment by bradydjohnson** [comment] 2020-01-24 01:55
So strange. Must've been a one-time thing. I haven't noticed it again since
closing/restarting Anki. I'll let you know if I see it again.


*Brad Johnson*
MD/MPH Candidate, Class of 2023
Tulane University School of Medicine

**Comment by glutanimate** [comment] 2020-01-25 14:16
That's good (although somewhat disconcerting) to hear! I guess as far as issues go, this is probably on the harmless side of things, but still, would love to figure out what happened there. Anyway, I think I'll close this issue report for now, but if you happen to stumble on this again, please feel free to reopen it at any point!

Thanks again for taking the time to file bug report like this. It's really appreciated!

**Closed as completed by glutanimate** 2020-01-25 14:16 UTC
Labels: bug, more info needed
